// import './06enum'
// import './07interface_object'
// import './08interface_fun'
// import './09function'
// import './10class1'
// import './11class2'
// import './12class_interface'
// import './14generics_class'
// import './15typeCheck1'
// import './16typeCheck2'
// import './17typeCheck3'
// import './18AdvancedFeatures1'
// import './part1/19AdvancedFeatures2'
import './part2/24statementMerger'

let hello : string = 'Hello ts'
document.querySelectorAll('.app')[0].innerHTML = hello
